VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
#TAP_DANCE_ENABLE = yes
#COMBO_ENABLE = yes
#KEY_OVERRIDE_ENABLE = yes
#QMK_SETTINGS = yes
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

